version: '3.8'  # Specify the Compose file version

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyPass@word"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
    restart: unless-stopped
